### ISSUE TITLE
Missing concrete implementation of 'Repository.repositoryFor'. Try implementing the missing method, or make the class abstract.

### ISSUE THREAD

**Issue by sooxt98** [flutterdata/flutter_data_todos#1]
![image](https://user-images.githubusercontent.com/13378059/83976127-b0506200-a92a-11ea-90b8-e9d5ae2a8cf3.png)

**Comment by frank06** [comment]
Sorry about that! I'll be pushing out a new FD version today or tomorrow, and update this repo to the latest. I'll make sure this bug is fixed.

**Comment by sooxt98** [comment]
@frank06 i think i solved it by running `flutter packages pub run build_runner build --delete-conflicting-outputs`

**Comment by sooxt98** [comment]
and plz don't use relative path when including the lib

**Comment by frank06** [comment]
What do you mean?

**Comment by sooxt98** [comment]
@frank06 it refers to your pc path instead of the package
![image](https://user-images.githubusercontent.com/13378059/83976691-230f0c80-a92e-11ea-98d6-57f69bd6ac56.png)

**Comment by frank06** [comment]
Ah, good catch. Will fix. Thank you!
