### ISSUE TITLE
about watchUsers() not update the isLoading

### ISSUE THREAD

**Issue by yixiangfeng** [flutterdata/flutter_data_todos#4]
when i pass the `state` to the `TodoList ` after response is success. the `isLoading` still is true no update to the false ;
The method I used is wrong or bug?
i try to use debug mode in vscode.
have some record you can take a look.

[picture with state in TodoList]
[https://ibb.co/89S499q](url)
nextstep i click continue the widget keep return  `CircularProgressIndicator()` and no any update
```
class TodoScreen extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final state = useProvider(
      watchUsers(),
    );

    return RefreshIndicator(
      onRefresh: () async {
        return context.refresh(
          watchUser(
            1,
            params: {'_embed': 'todos'},
            alsoWatch: (user) => [user.todos],
          ),
        );
      },
      child: TodoList(state),
    );
  }
}

class TodoList extends HookWidget {
  final DataStateNotifier<List<User>> state;
  TodoList(this.state, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (state.state.hasException) {
      return Text(state.state.exception.toString());
    }
    if (state.state.isLoading) {
      return Center(child: const CircularProgressIndicator());
    }
    return Text('data');
  }
}
```

**Comment by frank06** [comment]
I just pushed a completely updated version of this example based on the latest `0.6.0` release. All these issues should be fixed. Could you reopen the issue if you are still experiencing problems?
