### ISSUE TITLE
Encoded endpoint URL

### ISSUE THREAD

**Issue by DiegoCarvalho75** [flutterdata/flutter_data_todos#5]
Trying to run this demo i get an error. I think it's  because the encoded endpoint URL

I'm running this on Windows desktop

[users] GET https://my-json-server.typicode.com/%5Cflutterdata%5Cdemo%5Cusers%5C1?_embed=todos [HTTP 404]

flutter: [flutter_data] [users] Error: DataException: FormatException: Unexpected character (at character 1)
<!DOCTYPE html><html><head><meta charSet="utf-8" /><meta name="viewport" co...
^
  [HTTP 404]

Any ideia what is causing this? Thanks

**Comment by frank06** [comment]
Just released FD 1.4.0 and updated this app: https://github.com/flutterdata/flutter_data_todos/commit/4d74b988e0b72162c21bba00cfd8fbaa12769707

Could you try pulling from `master` and trying again? I think this issue was fixed but I have no Windows to test with.

**Comment by frank06** [comment]
Please reopen if the issue persists

**Comment by DiegoCarvalho75** [comment]
I have updated and it's working fine. Thanks
