### ISSUE TITLE
How to set default if local is null?

### ISSUE THREAD

**Issue by huang12zheng** [flutterdata/flutter_data_todos#6]
I don't know how to set the initial defaults.
Until I found https://github.com/rrousselGit/riverpod/issues/329#issuecomment-879019544
So I pr a demo about switch theme.

But, It maybe not be best practices.

**Comment by frank06** [comment]
Declare:

```dart
final initializerProvider = FutureProvider<bool>((ref) async {
  await ref.container.refresh(repositoryInitializerProvider.future);
  // do other async work
});
```

Use:

```dart
  ref.watch(initializerProvider).when(...)
```
